# Generated by Django 3.1.1 on 2024-01-09 11:16

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20240109_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='pass', max_length=150)),
                ('user_type', models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student')], default=1, max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('status', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(blank=True)),
                ('academic_qualification', models.TextField(blank=True)),
                ('work_experience', models.TextField(blank=True)),
            ],
            managers=[
                ('objects', main_app.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='academic_qualification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_experience',
            field=models.TextField(blank=True),
        ),
    ]
